name: Manual Publish

on:
  workflow_call:
    inputs:
      tag:
        description: 'Tagged version to release on NPM'
        default: ''
        required: false
        type: string

jobs:
  manual-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'

      - name: Update NPM to latest
        run: npm install npm@latest -g

      - name: Print Node.js and NPM version
        run: |
          node -v
          npm -v

      - name: Install dependencies
        run: npm ci

      - name: Build package
        run: npm run build

      - name: Create .npmrc
        run: |
          echo "registry=https://registry.npmjs.org/" > .npmrc
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}" >> .npmrc

      - name: NPM whoami
        run: npm whoami

      - name: Publish package
        run: |
          if [ "${{ inputs.tag }}" != "" ]; then
            npm publish --workspaces --tag $(echo "${{ inputs.tag }}" | sed 's/^v//')
          else
            npm publish --workspaces
          fi
