name: Manual Publish

on:
  workflow_call:
    inputs:
      prerelease:
        description: 'Publish as prerelease'
        default: false
        required: false
        type: boolean

jobs:
  manual-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: 24
          registry-url: 'https://registry.npmjs.org'

      - name: Update NPM to latest
        run: npm install npm@latest -g

      - name: Print Node.js and NPM version
        run: |
          node -v
          npm -v

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Build package
        run: npm run build

      - name: Publish package
        run: |
          if [ "${{ inputs.prerelease }}" == true ]; then
            npm publish --provenance --access public --workspaces --tag next
          else
            npm publish --provenance --access public --workspaces
          fi
